### PR TITLE
Render spinner before fetching data through AJAX

### PR DESCRIPTION
**Pull request by nikolalsvk**
Next step is to make spinner rendering optional. I plan on doing that by passing in the path to spinner partial somewhere in the app and then trying to render it with all the jQuery stuff.

### CODE REVIEW

**Comment by kaspergrubbe** [comment]
@nikolalsvk Do you want to take this project over?

**Comment by nikolalsvk** [comment]
@kaspergrubbe Sure, that would be cool.

**Comment by kaspergrubbe** [comment]
@nikolalsvk Do you have a user on Rubygems? Am I using the right e-mail address?

screenie_1487612063_1595929

**Comment by nikolalsvk** [comment]
@kaspergrubbe I've created one just now, `nikolalsvk` is the handle and that is the email `nikolaseap@gmail.com`

**Comment by kaspergrubbe** [comment]
Done!

```
Owner added successfully.
Owners for gem: render_async
- nikolaseap@gmail.com
- kawsper@gmail.com
```

**Pull request closed without merging**
